### PR TITLE
Remove other workflows

### PR DESCRIPTION
**Pull request by bdotdub**

### CODE REVIEW

**Review by seedlessmedia — APPROVED** [review]

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Review by seedlessmedia — APPROVED** [review]

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
$mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergepr

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Comment by bdotdub** [comment]
#mergeit

**Pull request merged**
